version: '3.1'
services:
  nginx:
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    volumes:
      - nodestatic:/usr/src/public
    depends_on:
      - node
    links:
      - node
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  node:
    build: .
    restart: always
    volumes:
      - nodestatic:/usr/src/app/public
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
volumes:
  pgdata:
  nodestatic: